### ISSUE TITLE
Create hash grid(s)

### ISSUE THREAD

**Issue by asalexan** [wayne-wu/webgpu-crowd-simulation#1]
- [x] research hash grids and develop plan
- [x] build grid and visualize
- [x] calcHash kernel
- [x] sort particles based on hash values
- [x] find start and end ptrs for each cell
- [x] incorporate into existing compute shaders

**Comment by wayne-wu** [comment]
This pdf talks about hash grid: https://developer.download.nvidia.com/assets/cuda/files/particles.pdf
