### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by asalexan** [wayne-wu/webgpu-crowd-simulation#34]
- “Traditional collision response” between predicted position and nearest point on obstacle
- C(xi, xj) = ||xi - xj|| - (ri + rj) >= 0
- Where x_i is predicted position and x_j is nearest obstacle pt (remove r_j)
- Collision point has infinite mass

**Comment by wayne-wu** [comment]
TODO:
* Improve obstacle behavior
* Add lambertian shading for obstacles
* Maybe add cylinder obstacles?
